# .travis.yml
language: node_js

node_js:
  - '8'

branches:
  only:
    - master

cache:
  yarn: true

script:
  - cd website && yarn install && yarn build

deploy:
  provider: script
  script: bash ../scripts/deploy.sh
  on:
    branch: master
